### PR TITLE
Moved Injectable.js to injectable.js

### PR DESCRIPTION
**Pull request by mkusher**
when trying to import 'ng-forward' on linux with ext4 fs(case-sensitive) I get:
```
ERROR in ./~/ng-forward/dist/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./decorators/providers/injectable in ./node_modules/ng-forward/dist
 @ ./~/ng-forward/dist/index.js 41:37-81

ERROR in ./~/ng-forward/dist/classes/provider.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../decorators/providers/injectable in ./node_modules/ng-forward/dist/classes
 @ ./~/ng-forward/dist/classes/provider.js 31:37-82

ERROR in ./~/ng-forward/dist/util/get-injectable-name.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../decorators/providers/injectable in ./node_modules/ng-forward/dist/util
 @ ./~/ng-forward/dist/util/get-injectable-name.js 13:37-82
```
When I've moved Injectablejs to injectable.js most of the test have passed

### CODE REVIEW

**Comment by timkindberg** [comment]
Not sure why the bubbling is broken all of a sudden... but we saw that too.

Looks good, thanks!

**Comment by timkindberg** [comment]
I thought only jasmine skips on xit... in mocha its it.skip. it probably skips because it doesn't recognize the xit keyword.

**Comment by MikeRyan52** [comment]
Mocha can do either.

**Comment by timkindberg** [comment]
@mkusher after talking with @MikeRyan52 we aren't going to merge this because its already fixed in the typescript branch that we are working on right now. Thanks for submitting though!

**Pull request closed without merging**
