### PR TITLE
fix(build): Remove sinon-chai from karma frameworks

### PR DESCRIPTION
**Pull request by brandonroberts**
Fixes errors with build

### CODE REVIEW

**Comment by timkindberg** [comment]
Hmm build is still broken. I've been trying to fix it for s couple days now. Is this PR trying to fix it?

If you look at the PR called issue-82 you can see I've tried upgrading babel. But both of our PRs are still failing on CI. Any ideas?

**Comment by brandonroberts** [comment]
Yep. I had gotten the build to work locally after upgrading babel-core, but it was using npm 2.14.7 instead of npm 3. I'll try to replicate it locally with npm 3 and see where it goes

**Comment by brandonroberts** [comment]
Hmm. This works locally, but fails in Travis

**Comment by brandonroberts** [comment]
The current issue is that Travis uses Chromium version 37, which doesn't support [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set). Support for Set wasn't added until Chrome 38.

**Comment by timkindberg** [comment]
If you can keep looking at this it would be great. I will not have time for several days still :(

**Comment by brandonroberts** [comment]
@timkindberg will do

**Comment by brandonroberts** [comment]
@timkindberg @MikeRyan52 build errors are fixed. Something is going on with the test suite that needs more checking on.

**Comment by timkindberg** [comment]
Oh awesome, and we got Symbols back!

**Pull request merged**
