### PR TITLE
Attempt for fixing unit tests

### PR DESCRIPTION
**Pull request by david-gang**
Hi all,
I know this project is abandoned but i have an important project written with this infra structure and have to maintain this module.
What i want to achieve is that i can upgrade the rxjs version to beta 10. i want to use angular with rxjs and fear that multiple versions of rxjs will screw things up.

Thanks,
David

### CODE REVIEW

**Comment by david-gang** [comment]
I don't know why travis is not run

**Comment by timkindberg** [comment]
What is this PR doing? just modifying a path to have /lib?

Remember you can always just fork the repo :)

**Comment by david-gang** [comment]
Yes. Therefore everything downstream works. As you can see the build is failing before this modification.

**Comment by timkindberg** [comment]
You feel pretty good about it? I can merge it but don't have time to really check. So if you can say you feel confident it needs to be added then I will merge it.

**Comment by david-gang** [comment]
I checked the diff if the resulting files and they were mostly the same. There were small changes in the dist file, but i plugged the resulting file in the node modules folder and everything worked.

**Comment by timkindberg** [comment]
Alright... I merged it... let's see if it works. Please submit a follow up PR if we need to revert or anything.

**Comment by david-gang** [comment]
Great :+1:

**Pull request merged**
